### ISSUE TITLE
"SyntaxError: Cannot use import statement outside a module" when trying Quickstart

### ISSUE THREAD

**Issue by akegaviar** [portis-project/web-sdk#51]
Trying to run an example by following your [Quick Start](https://docs.portis.io/#/quick-start).

The error I get is:

```
(node:19592) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
/root/portis.js:1
import Portis from "@portis/web3";
^^^^^^
SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

My environment:
- node v13.5.0
- web3@1.2.4

**Comment by tomteman** [comment]
I think it's because your environment doesn't support ES modules.
You can use CommonJS require function instead.
Keep in mind that if you do any SS rendering, you should follow the instructions here:
https://docs.portis.io/#/sever-side-rendering
